### PR TITLE
Fixing missing tap=true & title/body in foreground

### PR DESCRIPTION
**Pull request by jfougere**
This PR brings the following changes:

- tap=true is added when notification are tapped by user in 2 cases:
  - resuming a background app
  - cold starting the app
- notification callback is not done anymore when resuming an app (previously even without tapped notification, the callback was called)
- Notification title & body are added to the data passed to the javascript call back when notification is received in foreground. Those fields are put as: data.title & data.body

### CODE REVIEW

**Comment by hassanthegooner** [comment]
Tested and it works! 
Thanks

**Comment by hassanthegooner** [comment]
Just wanted to add that prior to using your code, onNotificationOpen was not being called when tapping a notification while the app is closed (cold) on Android. Your changes seem to have fixed it.

**Comment by jfougere** [comment]
@hassanthegooner Thanks for the feedback

Unfortunately this repo don't seem to be active at all and I have little hope that the PR will be merged any time soon.

**Comment by robertarnesson** [comment]
@jfougere can you fix the readme? most of its contents has been removed in the pr

**Comment by jfougere** [comment]
@robertarnesson done. Sorry for that.

**Comment by Screeze** [comment]
Would be nice if you could merge this, I also need the values in my app

**Comment by emilianoglucero** [comment]
Hello, is the "tap=true" attribute working right now ?
I've installed the plugin and I can't see this attribute in my incoming payload.
Thank you !

**Pull request merged**
