### PR TITLE
Make grantPermission api to repond user decision in iOS environment

### PR DESCRIPTION
**Pull request by JCloudYu**
I've modified the grantPermission api to make the api be able to respond the user decision

### CODE REVIEW

**Comment by tgensol** [comment]
I was looking for that ! I will try it soon thanks 👍

**Comment by dasilvathom** [comment]
Any news ? Because this modification will be very helpful 👌

**Comment by tgensol** [comment]
It is working very well on my side, thanks !

**Comment by tgensol** [comment]
@robertarnesson What do you think about this one ? It is really useful on my side and works as expected

**Comment by rolinger** [comment]
triple thumbs up.

**Comment by rolinger** [comment]
@JCloudYu @robertarnesson  - what is the new documentation for grantPermission()...is it a standard call back?  Ie:  grantPermission(success(), fail()) ;   ??

**Comment by damianobarbati** [comment]
great!! +1
does it take a callback or what?

**Comment by wilfredonoyola** [comment]
It is work well for me! Thanks.

**Comment by gecko-8** [comment]
For those stumbling onto this, the command format is:
```
window.FirebasePlugin.grantPermission(function() {
    // User approved access
}, function() {
    // User denied access
});
```

**Comment by obkdev** [comment]
@gecko-8 This is a great fix, to a point.. Where you've left the comment "// User approved success" I'm calling another method. I'm getting an error that says [Log] Error in Success callbackId: FirebasePlugin1296077761 : TypeError: null is not an object (evaluating 'this.localLoginAndLoad') (cordova.js, line 1732) 'this.localLoginAndLoad' is the method I want to call post success of grantPermission(). 

Do you have any idea how to overcome this problem? Thanks in advance!

**Comment by gecko-8** [comment]
@obkdev Sorry, but without seeing your code it's pretty hard to tell what the error might be. It really sounds like an error in your localLoginAndLoad method or how it's called.

**Pull request merged**
