### PR TITLE
Firebase Analytics & Installation Improvements

### PR DESCRIPTION
**Pull request by Chuckv01**
- Created separate installation variables for iOS and Android app parameters
- Initial Firebase Analytics Support
- Fixed bug when uninstalling the plugin on the iOS platform (previously uninstalling the plugin would delete the entire app directory)
- Fixed issue on iOS where `GoogleService-Info.plist` would have to be manually added to the build target. 
- `GoogleService-Info.plist` now resides within the Resources directory on iOS
- Updated README with more details on installation

### CODE REVIEW

**Comment by robertarnesson** [comment]
thx for the ios fixes. I have integrated most of your changes, except:

* I dropped the conf variables to make it easier to install. Instead the plugin will simply look for GoogleService-Info.plist and google-services.json in the project root and copy them to the right place

* on IOS, [FIRApp configure] is the entrypoint for the entire SDK, without it the FCM handlers are not triggered etc. Therefore analytics is now enabled as default on both platforms as part of pluginInitialize, and startAnalytics has been removed

**Comment by Chuckv01** [comment]
@robertarnesson Great idea copying the files. WAY easier to setup. One issue though. We will still need the ANDROID_GOOGLE_APP_ID parameter on plugin installation. In plugin.xml this line copies the google app id to the android `resources/vales/strings.xml` file:

```
<config-file parent="/*" target="res/values/strings.xml">
    <string name="google_app_id">$ANDROID_GOOGLE_APP_ID</string>
</config-file>
```

This is needed on android for analytics to function properly. If you try to init analytics without this parameter on android you will get this error message in logcat:

```
06-27 09:33:08.460 E/FA      (25199): GoogleService failed to initialize, status: 10, Missing google app id value from from string resources with name google_app_id.
06-27 09:33:08.460 E/FA      (25199): Scheduler not set. Not logging error/warn.
06-27 09:33:08.480 V/FA      (25199): Registered activity lifecycle callback
06-27 09:33:08.510 E/FA      (25199): Measurement Service called without google_app_id
06-27 09:33:08.520 E/FA      (25199): Uploading is not possible. App measurement disabled
```

**Comment by robertarnesson** [comment]
@Chuckv01 yes you are right. I'll update the hook. we can read the app id from google-services.json in there and write it to strings.xml

**Comment by Chuckv01** [comment]
@robertarnesson I initially tried to do that from the hook. However, I ran into trouble parsing the xml. ><

When you want to add/remove the plugin, or the project is copied from a previous source, the app_id gets duplicated or out-of-date. If you're good at regex'es you might be able to hack together something relatively stable. 

IMHO it is reasonable to ask people to provide that parameter at installation and use the plugin.xml `config-file` to copy it to the strings.xml file. That's the purpose of `config-file` after all :)

**Comment by Chuckv01** [comment]
@robertarnesson Unless you want to include an xml parser in the hook script. Don't know about that though... sounds hacky.

**Comment by robertarnesson** [comment]
@Chuckv01 I'm thinking I could use plugin.xml to insert a placeholder value then just search/replace in the hook. I'll play around with it. An extra variable is not a dealbreaker but if its possible to keep it clean without too much effort I'd prefer that

**Comment by Chuckv01** [comment]
@robertarnesson Yeah great to have less installation work. I was running into problems with the insert then find/replace approach. Cordova was duplicating the app tag on prepare. I was probably missing something though.

**Comment by robertarnesson** [comment]
@Chuckv01 seems like this did the trick a189c1c

**Comment by Chuckv01** [comment]
@robertarnesson You're the man. Working great for me.

**Pull request closed without merging**
