### PR TITLE
Fix cordova-android 8.0.0 Crashlytics bug

### PR DESCRIPTION
**Pull request by diogeneshamilton**
Fixes issue where upgrading google services fixes issue for cordova-android 8.0.0 \
Fixes https://github.com/arnesson/cordova-plugin-firebase/issues/1006

### CODE REVIEW

**Comment by ArnaudSpanneut** [comment]
Thanks for the fix @diogeneshamilton 🙏
@soumak77 Do you think you could merge it and create a new version?

**Comment by adipascu** [comment]
@kaynz Seems like the project already has [that line added inside the runtime repositories block](https://github.com/arnesson/cordova-plugin-firebase/blob/db3b661fc7fe23694794c9d4e8f9f10c8eb7d649/src/android/build.gradle#L14).

Are you talking about adding it inside the buildscript > repositories block [right here ](https://github.com/arnesson/cordova-plugin-firebase/blob/db3b661fc7fe23694794c9d4e8f9f10c8eb7d649/src/android/build.gradle#L4)?

I do not seem to require your change while using this PR.
I have cordova-android 8.0.0 with cordova 8.1.2 .

**Comment by kaynz** [comment]
@adipascu 
> Are you talking about adding it inside the buildscript > repositories block [right here ](https://github.com/arnesson/cordova-plugin-firebase/blob/db3b661fc7fe23694794c9d4e8f9f10c8eb7d649/src/android/build.gradle#L4)?

This one.

> I do not seem to require your change while using this PR.
Maybe you have another plugin which sets this parameter?

**Comment by adipascu** [comment]
@kaynz 
I just did a test with a blank project with cordova-android 8.0.0 and this PR, it built ran and correctly (checked Firebase by generating the an ID token).
I published the [test project here](https://github.com/adipascu/cordova-firebase-test) if you need it.

I think I get the dependency we are talking about from [cordova-android 8.0.0](https://github.com/apache/cordova-android/blob/rel/8.0.0/bin/templates/project/build.gradle#L23) .

I think the issue is specific with your setup, try removing the `platforms` and `plugins` folders and running `cordova prepare`.

**Comment by kaynz** [comment]
@adipascu 
Thanks, `rm -rf platforms plugins && cordova prepare` is my default workflow before posting on github.
I'll try out your test project. If it works, as you say, I'll try to add my plugins one by one to identify the one which breaks the project - I got like 10 or 15 plugins.

**Comment by kaynz** [comment]
Yea, fixed it! The changes in this PR are enough to fix the mentioned problem :)

Not sure when this will be merged though..

**Comment by l3ender** [comment]
Is this something that can be merged/release? :)

**Comment by briantq** [comment]
Since the tests are failing I don't want to create a new version as it could break other people.  That being said, I can confirm this does resolve the same issue I encountered when moving to Android 8.0.0, so merging it does make sense.  I will try to create a branch that users can point to that will specifically pick up this fix

**Comment by briantq** [comment]
I create a new branch for this fix since the tests are failing and don't want to version it in case we break existing installs.

To use this fix, simply run
`cordova plugin remove cordova-plugin-firebase`
followed by
`cordova plugin add https://github.com/arnesson/cordova-plugin-firebase.git#android-google-services-update`

This will add a reference directly to the branch with the fix (current master + fix) instead of a specific version.

**Comment by l3ender** [comment]
@briantq Is it possible to create a beta or RC version? This would allow it to be published to NPM registry for consumption with just a version number, and not need to reference a git+https dependency (we encounter a lot of issues with those).

Thanks!

**Comment by tmk1991** [comment]
When can we expect this rolled into a new plugin release?

**Comment by ajeetsharma16** [comment]
I updated `cordova-plugin-firebase `with `cordova plugin add https://github.com/arnesson/cordova-plugin-firebase.git#android-google-services-update`, still I have same issue with cordova-android 8.0.0

**Comment by tmk1991** [comment]
Drop down to a 7.x version. 8 is wicked unstable

**Comment by l3ender** [comment]
@briantq Is it possible to get a patch or minor release for this fix? Thanks!

**Comment by khalilbhs** [comment]
for me version 2.0.0 of firebase makes me feel

**Comment by nelson6e65** [comment]
> I create a new branch for this fix since the tests are failing and don't want to version it in case we break existing installs.
> 
> To use this fix, simply run
> `cordova plugin remove cordova-plugin-firebase`
> followed by
> `cordova plugin add https://github.com/arnesson/cordova-plugin-firebase.git#android-google-services-update`
> 
> This will add a reference directly to the branch with the fix (current master + fix) instead of a specific version.


I tried this, but I get another error now: 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
```
<details>

```
> Task :app:processDebugResources

C:\Users\Nelson\Documents\GitHub\linkingcard\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginInstanceIDService.java:6: error: cannot find symbol
import com.google.firebase.iid.FirebaseInstanceIdService;
                              ^
  symbol:   class FirebaseInstanceIdService
  location: package com.google.firebase.iid
C:\Users\Nelson\Documents\GitHub\linkingcard\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginInstanceIDService.java:8: error: cannot find symbol
public class FirebasePluginInstanceIDService extends FirebaseInstanceIdService {
                                                     ^
  symbol: class FirebaseInstanceIdService
C:\Users\Nelson\Documents\GitHub\linkingcard\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:610: error: method getByteArray in class FirebaseRemoteConfig cannot be applied to given types;
                        : FirebaseRemoteConfig.getInstance().getByteArray(key, namespace);
                                                            ^
  required: String
  found: String,String
  reason: actual and formal argument lists differ in length
C:\Users\Nelson\Documents\GitHub\linkingcard\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:629: error: method getValue in class FirebaseRemoteConfig cannot be applied to given types;
> Task :app:compileDebugJavaWithJavac FAILED
33 actionable tasks: 33 executed
                        : FirebaseRemoteConfig.getInstance().getValue(key, namespace);
                                                            ^
  required: String
  found: String,String
  reason: actual and formal argument lists differ in length
C:\Users\Nelson\Documents\GitHub\linkingcard\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:686: error: no suitable method found for setDefaults(Map<String,Object>,String)
                        FirebaseRemoteConfig.getInstance().setDefaults(defaultsToMap(defaults), namespace);
                                                          ^
    method FirebaseRemoteConfig.setDefaults(Map<String,Object>) is not applicable
      (actual and formal argument lists differ in length)
    method FirebaseRemoteConfig.setDefaults(int) is not applicable
      (actual and formal argument lists differ in length)
C:\Users\Nelson\Documents\GitHub\linkingcard\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:885: error: cannot find symbol
                        myTrace.incrementCounter(counterNamed);
                               ^
  symbol:   method incrementCounter(String)
  location: variable myTrace of type Trace
C:\Users\Nelson\Documents\GitHub\linkingcard\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginInstanceIDService.java:17: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 48s
C:\Users\Nelson\Documents\GitHub\linkingcard\platforms\android\gradlew: Command failed with exit code 1 Error output:
Note: C:\Users\Nelson\Documents\GitHub\linkingcard\platforms\android\CordovaLib\src\org\apache\cordova\engine\SystemCookieManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Users\Nelson\Documents\GitHub\linkingcard\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginInstanceIDService.java:6: error: cannot find symbol
import com.google.firebase.iid.FirebaseInstanceIdService;
                              ^
  symbol:   class FirebaseInstanceIdService
  location: package com.google.firebase.iid
C:\Users\Nelson\Documents\GitHub\linkingcard\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginInstanceIDService.java:8: error: cannot find symbol
public class FirebasePluginInstanceIDService extends FirebaseInstanceIdService {
                                                     ^
  symbol: class FirebaseInstanceIdService
C:\Users\Nelson\Documents\GitHub\linkingcard\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:610: error: method getByteArray in class FirebaseRemoteConfig cannot be applied to given types;
                        : FirebaseRemoteConfig.getInstance().getByteArray(key, namespace);
                                                            ^
  required: String
  found: String,String
  reason: actual and formal argument lists differ in length
C:\Users\Nelson\Documents\GitHub\linkingcard\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:629: error: method getValue in class FirebaseRemoteConfig cannot be applied to given types;
                        : FirebaseRemoteConfig.getInstance().getValue(key, namespace);
                                                            ^
  required: String
  found: String,String
  reason: actual and formal argument lists differ in length
C:\Users\Nelson\Documents\GitHub\linkingcard\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:686: error: no suitable method found for setDefaults(Map<String,Object>,String)
                        FirebaseRemoteConfig.getInstance().setDefaults(defaultsToMap(defaults), namespace);
                                                          ^
    method FirebaseRemoteConfig.setDefaults(Map<String,Object>) is not applicable
      (actual and formal argument lists differ in length)
    method FirebaseRemoteConfig.setDefaults(int) is not applicable
      (actual and formal argument lists differ in length)
C:\Users\Nelson\Documents\GitHub\linkingcard\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:885: error: cannot find symbol
                        myTrace.incrementCounter(counterNamed);
                               ^
  symbol:   method incrementCounter(String)
  location: variable myTrace of type Trace
C:\Users\Nelson\Documents\GitHub\linkingcard\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginInstanceIDService.java:17: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors

FAILURE: Build failed with an exception.
```

</details>

:cry:


```
platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginInstanceIDService.java:17: error: method does not override or implement a method from a supertype
    @Override
```


```
branch-cordova-sdk 3.2.0 "branch-cordova-sdk"
cordova-clipboard 1.3.0 "Clipboard"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-facebook4 4.2.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic 5.3.1 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-queries-schemes 0.1.1 "App Queries Strings"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.7 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"
```

**Pull request merged**
