### PR TITLE
update readme to include resource file install

### PR DESCRIPTION
**Pull request by mohamedsharaf**
update readme to include resource file install

### CODE REVIEW

**Comment by soumak77** [comment]
@mohamedsharaf this seems like something the plugin should be handling.  Please provide more details as to why you needed to add this to your app config.

**Comment by mohamedsharaf** [comment]
look at this other pull request i also removed it from plugin it conflicts

 GoogleService-Info.plist this will cause error when u have it already add in config.xml 
and remove platform ios and re add it u will get error 


https://github.com/arnesson/cordova-plugin-firebase/pull/691

**Comment by mohamedsharaf** [comment]
i think u missed what i did in the request https://github.com/arnesson/cordova-plugin-firebase/pull/691 
i removed the file merger from resources and made it in config.xml so i added to readme 

i removed because it conflicts with other plugin if file already exist in the resources your plugin will not install and through output error 

to re make the error 

create new cordova project add the resource file GoogleService-Info.plist to config.xml and in folder proejct 

then add new platform 

cordova platform add ios

cordova plugin add cordova-plugin-firebase

you will see plugin will not install file already exist

**Comment by soumak77** [comment]
Do you have a specific plugin that conflicts?  The example you provided does not install another plugin and therefore there is no need to add the file to config.xml.

**Comment by mohamedsharaf** [comment]
i made test rep
https://github.com/mohamedsharaf/cordova-plugin-firebase-test

run 

npm install

cordova platform add ios

cordova plugin add cordova-plugin-firebase

```
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-firebase': CordovaError: Uh oh!
File already exists at destination "/Users/mohamed/data/test/test/platforms/ios/HelloCordova/Resources/GoogleService-Info.plist" for resource file specified by plugin cordova-plugin-firebase in iOS platform
    at install (/Users/mohamed/data/test/test/platforms/ios/cordova/lib/plugman/pluginHandlers.js:64:23)
    at ActionStack.process (/Users/mohamed/data/test/test/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/mohamed/data/test/test/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/mohamed/data/test/test/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at Api.addPlugin (/Users/mohamed/data/test/test/platforms/ios/cordova/Api.js:234:10)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
Error: Uh oh!
File already exists at destination "/Users/mohamed/data/test/test/platforms/ios/HelloCordova/Resources/GoogleService-Info.plist" for resource file specified by plugin cordova-plugin-firebase in iOS platform

```

**Comment by soumak77** [comment]
Remove the `resource-file` lines from config.xml and the build is fixed.  I still haven't heard a valid reason for why these lines need to be added to config.xml.

**Pull request closed without merging**
