### PR TITLE
Removed initRemoteConfig method

### PR DESCRIPTION
**Pull request by kurtsergey**
Fixed misconception about inititalization/activation

### CODE REVIEW

**Comment by soumak77** [comment]
@kurtsergey I feel this change should depend on a configuration variable so that it can be turned on/off based the the app's requirements. Some apps may depend on this functionality, so we can't just remove it entirely.

**Comment by kurtsergey** [comment]
@soumak77 Apps cannot depend on this functionality because there is no 'init' functionality in native RemoteConfig modules.

**Comment by soumak77** [comment]
@kurtsergey understood.  Does this fix any open issues that can be closed once merged?

**Comment by kurtsergey** [comment]
No, I cannot find any issues about it.

**Comment by kurtsergey** [comment]
@soumak77  Would you please publish release?

**Comment by soumak77** [comment]
I will once #830 is tested and merged

**Comment by herrskytte** [comment]
I get RemoteConfig isn't initalised...
Got the same for analytics, performance etc but fixed it with initX. But there should be initRemoteConfig too?

Get the error when calling setConfigSettings(..)

**Comment by briantq** [comment]
@herrskytte the analytics and performance inits are still in the latest version of the plugin.  These were added by accident as they change the defualt behavior of this plugin.  We are working on reverting the code so users don't have to call in init method.

We have a pull request to remove them so if you could test and confirm if this resolves the issue, that would be great.  You can do this by:

1. Remove your initX in your code
2. `cordova plugin remove cordova-pluin-firebase`
3. `cordova plugin add https://github.com/briantq/cordova-plugin-firebase.git#revert-lazy-init`

If you could test with that branch and confirm that it works as expected, that would help us in merging the fix faster.

**Comment by herrskytte** [comment]
@briantq I am working behind a firewall, so I can only access Maven, not Github. Sorry. 

Sidenote: Yesterday I only got the error about RemoteConfig, but after resetting the platform the app now crashes on startup with a Java IllegalStateException: FirebaseApp is not initialized in this process .. Make sure to call FirebaseApp.initializeApp(Context) first. I get this both with and without the initX code

**Comment by briantq** [comment]
@herrskytte Can you run `cordova plugin list` to see which version of the plugin you are using?  Make sure you are using 2.X and you shouldn't hit that error

**Pull request merged**
