### PR TITLE
#374 commit for change color plugin

### PR DESCRIPTION
**Pull request by bhavinwebdesk**

### CODE REVIEW

**Comment by robertarnesson** [comment]
what is the purpose of this change?

**Comment by bhavinwebdesk** [comment]
Firebase plugin contains colors.xml and it is conflicts with other plugins that may contains same file name.
To avoid conflict and add plugin successfully, have to rename colors.xml to something else that is unique.

**Comment by robertarnesson** [comment]
could we not use the same method as in https://github.com/arnesson/cordova-plugin-firebase/pull/552?

**Comment by soumak77** [comment]
closing for cleanup, please resubmit PR if changes are still desired

**Pull request closed without merging**
