### PR TITLE
Upgrade Firebase to 5.7.0 and prune frameworks

### PR DESCRIPTION
**Pull request by briantq**
Related Issue #796

I updated the Firebase SDK to 5.7.0.  From what I can tell, it seems to be working.  I was able to test it in my application (which only references Messaging), but got everything to compile successfully.

### CODE REVIEW

**Comment by briantq** [comment]
@soumak77 Thanks for letting me know about the failing tests.  From what I can tell, it appears that the common resolution for Error code 65 when dealing with Frameworks is to remove and add the ios platform back again.  I believe this is because `cordova prepare` will add the Frameworks, but if they is a different version already there, it's likely going to cause problems.  I multiple issues with this error and the same solution [1](https://forum.ionicframework.com/t/ionic-build-ios-plugin-errors-exit-code-65/7274/18) [2](https://github.com/ionic-team/ionic-cli/issues/1060).

Is there some way we can modify the test to run that prior to running the tests?  Since I am just moving frameworks around and made a single line change, it seemed to make no sense why certain version of Cordova are failing...

If you want, I can include in the pull request an update to the Readme that mentions what to do if you see this error.

**Comment by soumak77** [comment]
@briantq I'm fine if we need to add `cordova prepare` to the tests, however, the tests run a clean install of the plugin on travis, so I wouldn't expect for that line to be needed.  It would be ideal if you can figure out the signing issue you were running into when running the iOS tests locally, so that you can troubleshoot without having to make changes to the PR and wait for the travis tests to run.

If you do find you need to add `cordova prepare`, I think it would need to go at the bottom of the file [platform-add.sh](https://github.com/arnesson/cordova-plugin-firebase/blob/master/test/platform-add.sh).  Feel free to add this line to see if it fixes the issue for the travis tests.  If not, just revert that change.

**Comment by soumak77** [comment]
@briantq you can also run just the iOS tests for a specific cordova version.  Here are all the iOS test commands:

`npm run test:cordova@6.5.0:ios@4.5.4`
`npm run test:cordova@7.1.0:ios@4.5.4`
`npm run test:cordova@8.0.0:ios@4.5.4`

Only the first two are failing on travis.  For whatever reason, the last test is fine.

**Comment by soumak77** [comment]
@briantq one last thing to be aware of is that the tests install cordova locally only, so it won't affect the cordova version you have installed globally on your system

**Comment by briantq** [comment]
@soumak77 I was able to get it working on another machine and running both 
`npm run test:cordova@6.5.0:ios@4.5.4
npm run test:cordova@7.1.0:ios@4.5.4`
completed successfully.  

Is there some where I can take a look at the automated test configuration?  I can try to figure out what's different on the CI build than my machine.  

If you have 2 minutes, would you mind running one of the tests on your machine from briantq:firebase-sdk-5.7.0.  I want to make sure I am not crazy.

**Comment by soumak77** [comment]
You can check out the travis configuration here: https://github.com/arnesson/cordova-plugin-firebase/blob/master/.travis.yml

I can respond to any comments in a timely manner but won't be able to help with development changes until after the weekend as I won't be near my development machine.

**Comment by soumak77** [comment]
I do see the iOS tests run on xcode 8.3.  What verision of xcode are you using? I dont know if many even still use xcode 8.x, so if we need to upgrade the xcode version on the tests it might be okay.

**Comment by soumak77** [comment]
I don't plan on releasing any new versions soon, so I'm ok with merging this PR so that others might be able to help out and test the changes without needing to use your fork.

The only change we might want to get in before that is adding back the auto-init of firebase. I can try to figure out which line(s) were removed by the Crashlytics PR and release a patch version before merging this PR.

**Comment by briantq** [comment]
@soumak77 we should definitely fix the firebase init first.  I am no longer blocked on my development as I can reference the branch directly from my fork.

Good call on the XCode version.  I am currently running 9.4.1.  Maybe that has something to do with it...  Still odd that one passes since it really is just copying frameworks.  I am shocked that cordova versions affect that.

**Comment by soumak77** [comment]
@briantq looks like updating the xcode version fixed the tests.  I'll merge this PR and publish v2.0.0 of this plugin once we get v1.1.4 out with the auto-init fix.

Would you happen to know what code needs to be added back to fix the auto-init issue?

**Comment by briantq** [comment]
Sweet, it was easy to try it.  I can separate out the XCode test update to a separate PR.

I agree it makes sense in a 2.0.0. 

I can look, there were a lot of changes.  We definitely need to modify FirebasePlugin.java.  I was looking at AppDelegate+FirebasePlugin.m and I don't think the PR changed the initialization at all on iOS.  If we get doc updates, we probably want to reflect that the initialization depends on which platform you are developing for.

**Comment by soumak77** [comment]
No need to split the xcode changes to a new PR as it is required to make this PR pass the tests, so it makes sense to keep it as part of this PR.

**Pull request merged**
