### PR TITLE
Fix for #499

### PR DESCRIPTION
**Pull request by amritk**
This is my attempted fix for the new android 7.0.0 update. Not sure if this works for all cases but its working for me.

### CODE REVIEW

**Comment by marcoramires** [comment]
Hi All,

Any news on this PR?

The plugin is breaking the build on cordova 7.0.

Cheers,
Marco

**Comment by kaynz** [comment]
This breaks support for older cordova-android versions. Could you update your PR to support this case?

**Comment by amritk** [comment]
@kaynz I am not sure how to do conditionals based on cordova-android version. Maybe someone more knowledgeable can step in.

**Comment by kaynz** [comment]
@amritk You'll find some help in this PR: https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/pull/189/files

**Comment by robertarnesson** [comment]
Fixed now in master. commit 039e29e

**Pull request closed without merging**
