### PR TITLE
Implement foreground notifications on Android

### PR DESCRIPTION
**Pull request by NoelDeMartin**
I completed some missing features on android reggarding notifications, as referenced in issue #82

### CODE REVIEW

**Comment by robertarnesson** [comment]
overall nice work! I have 2 things...

1) if the callback context is null or not is really not the same as the app being in foreground/background. There needs to be a proper check to check the apps state, just like on the IOS side.
2) we should also add "tap" true/false to the notification bundle to indicate if the notification was tapped or not

**Comment by NoelDeMartin** [comment]
I am thinking how to approach the foreground/background issue. Since we don't have an Activity associated with the plugin I am thinking on having an Application class, which would require to modify the AndroidManifest.xml file, but I am worried about this causing conflicts with other plugins, since there can only be one Application class per Android app.

Is there any other way to detect the status of the application other than handling onResume, onPause, etc.? I have seen the iOS approach within the AppDelegate but I don't know much about iOS and I am not sure if there is any direct equivalence of that in Android.

I'll think about it and try to come up with a solution :smile:

**Comment by robertarnesson** [comment]
I believe everything you need is in the plugin class. see e.g. http://www.polyglotprogramminginc.com/interacting-with-the-android-lifecycle-in-a-cordova-plugin/

**Comment by NoelDeMartin** [comment]
@robertarnesson I just implemented the changes you mentioned. Looking at the methods in CordovaPlugin class, I also noticed the plugin should override the onReset method in order to clear the pointers to notification and tokenRefresh contexts.

**Comment by robertarnesson** [comment]
very nice work! i'll merge and make a new release

**Pull request merged**
