### PR TITLE
Oreo notification channel fix: Fix the build issue in #603 by replacing a stray resource import with a generic resource get method.

### PR DESCRIPTION
**Pull request by keyz182**
Fix the build issue in #603 by replacing a stray resource import with a generic resource get method.

### CODE REVIEW

**Comment by soumak77** [comment]
@keyz182 the cordova-android v6 build is broken

**Comment by soumak77** [comment]
@keyz182 build is now broken for both v6 and v7.  By the way, the command `cordova platform add android@~6.0.0` will install the latest 6.x.x version (i.e. 6.2.3), so that does not need to be changed.

**Comment by keyz182** [comment]
Oh, oops, I hadn't realised github would auto-update here.

Oddly, ```cordova platform add android@~6.0.0``` was installing 6.0.0 for me locally. 

I'm a struggling a bit with Travis at the moment. For the code in this PR to work, it needs to build against SDK 26, but Travis seems stuck on 25. Also, the forcing 6.2.2 was because build-tools 26 doesn't work with previous versions. Do you have any suggestions?

**Comment by soumak77** [comment]
@keyz182 is there any way to make this feature only included running cordova-android v7?  Possibly via a cordova hook?

If this feature cannot be disabled in cordova-android v6, we can still include it and just release a new major version of the plugin.  If this is the case, I'd like to get some other PRs merged first that work for both cordova-android v6 and v7.

**Comment by keyz182** [comment]
@soumak77 
> Looks like SDK 26 is not supported by cordova-android v6: https://cordova.apache.org/docs/en/latest/guide/platforms/android

That's odd. I'm using cordova-android V6 in my app (it's an Ionic app, so 7+ isn't yet supported/breaks everything). I guess it "can work" but isn't supported.

> @keyz182 is there any way to make this feature only included running cordova-android v7? Possibly via a cordova hook?

I'm not massively familiar with cordova plugin writing, so I'm not sure. I can take a look though.

**Comment by soumak77** [comment]
@keyz182 what version of ionic are you using?  I'm using the latest version of ionic (v3.9.2) and it works perfectly fine with cordova-android v7.

In any case, spend some time on trying to get it to work for v6 and if you can't we'll wait for the next major release to include these changes.

**Comment by keyz182** [comment]
@soumak77 

>Looks like SDK 26 is not supported by cordova-android v6: https://cordova.apache.org/docs/en/latest/guide/platforms/android

Update: running locally, and setting ```cordova platform add android@~6.0.0``` in ```build-android-v6.sh``` it correctly picks up 26.

```
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms/android
        Package: com.example.hello
        Name: HelloWorld
        Activity: MainActivity
        Android target: android-26
```
It also builds completely. Not sure why I can't replicate on Travis.

**Comment by soumak77** [comment]
@keyz182 are you using cordova v6 or v7 locally?  Travis explicitly installs cordova v6 when testing cordova-android v6.

**Comment by keyz182** [comment]
> @keyz182 what version of ionic are you using? I'm using the latest version of ionic (v3.9.2) and it works perfectly fine with cordova-android v7.

The Ionic Pro build service we use doesn't support it currently (https://ionic.zendesk.com/hc/en-us/articles/360000020508-Android-builds-with-cordova-android-7-0-0-failing), and a few of the plugins we use (can't remember the list currently) don't work at all.

>In any case, spend some time on trying to get it to work for v6 and if you can't we'll wait for the next major release to include these changes.

Will try, time allowing.

**Comment by keyz182** [comment]
> @keyz182 are you using cordova v6 or v7 locally? Travis explicitly installs cordova v6 when testing cordova-android v6.

```
$ cordova --version
6.5.0
$ cordova platform ls
Installed platforms:
  android 6.4.0
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  ubuntu ~4.3.4
  webos ~3.7.0
```

**Comment by soumak77** [comment]
For some reason travis is picking up the latest cordova-android version as 6.2.3, yet 6.3.0 and 6.4.0 are also available.  Also, cordova-android 6.3.0 supports SDK 26 (https://github.com/apache/cordova-android/blob/master/RELEASENOTES.md#630-sep-25-2017)

Update the test scripts to explicitly install version cordova-android 6.4.0.  If it still picks up the wrong version, perhaps we need to update the list of repos cordova pulls from (not sure how to do this though).

**Comment by soumak77** [comment]
@keyz182 fyi, I just updated the PR to install 6.4.0.  Hopefully travis build passes now.

**Comment by keyz182** [comment]
@soumak77 I'd just created another branch on my repo to test that too :)

**Comment by keyz182** [comment]
@soumak77 That seems to have fixed the issue! :)

**Comment by soumak77** [comment]
@keyz182 awesome!  Thanks for your hard work on this!  I'll release a new minor version in a few days.  Until then you can install from github to test out the changes.

**Comment by keyz182** [comment]
@soumak77 I've got it pulling straight from my fork for now, but will switch over :)

**Pull request merged**
