### PR TITLE
prevent crashing on verificationFail

### PR DESCRIPTION
**Pull request by Hirbod**

### CODE REVIEW

**Comment by Hirbod** [comment]
Feel free to optimize this, I don't see any advantages providing the errorCode as string. If you want to do it right, It should be a JSON-Result anyway, like the iOS implementation. Currently, this single line is causing 600 crashes inside my analytics.

**Comment by soumak77** [comment]
I see. Line should be removed then instead of commented out. I'm on my phone so can't do this myself right now.

**Comment by Hirbod** [comment]
done

**Comment by soumak77** [comment]
Thanks for the fix. I'll publish a patch release soon.

**Pull request merged**
