### PR TITLE
Clear all notifications implementation for iOS & Android

### PR DESCRIPTION
**Pull request by Rignacio**
window.FirebasePlugin.clearAllNotifications()

### CODE REVIEW

**Comment by jarekskuder** [comment]
+1 i need it

**Comment by soumak77** [comment]
@Rignacio please update from master

**Comment by Troejborg** [comment]
+1

**Comment by shi11** [comment]
I updated from master here: https://github.com/shi11/cordova-plugin-firebase - not sure how to resubmit for the PR

**Pull request closed without merging**
