### PR TITLE
use install/uninstall hooks instead of add/remove hooks

### LINKED ISSUE #869: Cordova platform add does not run after_plugin_add hooks
**Describe the bug**
on cordova platform add android the system doesn't perform the necessary hooks to utilize android.

**To Reproduce**
*Scenario 1*

	cordova platform add android
	cordova plugin add cordova-plugin-firebase

Take note of: compare platforms/android/build.gradle 

*Scenario 2*

	cordova platform remove android
	cordova plugin add cordova-plugin-firebase
	cordova platform add android

**Scenario 1  can be built successfully scenario 2 will fail with the following statement**

	cordova build android

> FAILURE: Build failed with an exception.
>
> * Where:
> Script '*******/platforms/android/cordova-plugin-firebase/mobileweb-build.gradle' line: 33
>
> * What went wrong:
> A problem occurred evaluating project ':app'.
> Plugin with id 'com.google.gms.google-services' not found.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more 
> log output.
> 
> * Get more help at https://help.gradle.org

**Expected behavior**
Adding and removing platforms should have no side effect on how the system performs.

**Solution**
In plugin.xml i added the following script to perform the same actions as after_plugin_add on platform_add

	<hook src="scripts/after_plugin_add.js" type="after_platform_add" />

### PR DESCRIPTION
**Pull request by soumak77**
replaces PR #872

fixes #869

Co-Authored-By: @oborudko

### CODE REVIEW

**Comment by briantq** [comment]
@soumak77 since you refactored the scripts to be platform specific is there a reason you didn't do the same to the helpers. Seems odd to have some platform specific code in platform folders and other that is in a shared folder separated by only a naming convention.

**Comment by soumak77** [comment]
@briantq no specific reason.  I'll refactor the helper scripts as well.

**Comment by briantq** [comment]
@soumak77 on my train ride in I modified the script to put Google in allprojects so we follow the install guide to a T. I'll make a PR when I get into the office.

**Comment by soumak77** [comment]
@briantq probably best to first review and merge #886 so you can avoid merge conflicts

**Pull request merged**
