### PR TITLE
added verifyPhoneNumber (for Android), alwaysShowNotification, replacePrevNotifications

### PR DESCRIPTION
**Pull request by apptum**
last week firebase added phoneAuth to the [android sdk](https://firebase.google.com/docs/auth/android/phone-auth) and since the JavaScript implementation doesn't work for cordova (without nasty workarounds) I added it.

However, I've never written a cordova plugin (or something in JAVA) before, so maybe you want to have a look ;)

Works fine on Android 7.1.2.

### CODE REVIEW

**Comment by apptum** [comment]
last commit adds
### setAlwaysShowNotification (Android only?)

Shows notification when the app is in foreground.
Notifications behaves as if app is in background. That means the notification data is received in the JavaScript callback when the users taps the notification.

```
window.FirebasePlugin.setAlwaysShowNotification(true/false)
```

### setReplacePrevNotifications (Android only?)

Previous notifications are replaced by new ones. Data of old notifications is lost.

```
window.FirebasePlugin.setReplacePrevNotifications(true/false)
```

**Comment by rolinger** [comment]
heya @apptum  -  did you fork this?  Walk me through installing this please.   `setAlwaysShowNotification` - is it still for Android only?  What is the behavior on iOS?  I have yet to figure out how to process a payload on an inbound notification if the app is already open...if its closed or in the background then no problem, but opened in foreground I can't get find a way to see the payload.  I would ultiamtely prefer your new method, but at a minimum if I can get the payload while app is open then I could at least do some kind of custom pop up - have you figured this one out yet?

**Comment by GulinSS** [comment]
Does it relate to https://github.com/arnesson/cordova-plugin-firebase/pull/325?

**Comment by rolinger** [comment]
@apptum - this fork is crashing my app.  I installed this fork and added:

  window.FirebasePlugin.setAlwaysShowNotification(true) ;

I am sending test messages from FCM console to my device and everytime a message arrives it crashes my app - console shows now messages or errors.  With the app open and in the foreground, the app crashes/closes and a message appears on the Android: `"Unfortunately, APPNAME has stopped"`.

I did notice it created a "cordova-plugin-firebase" folder in the `appName/platforms/android` folder.   But I can't find any other crash files or logs.

**Comment by sajTempler** [comment]
As well when you try 
```
FirebasePlugin.verifyPhoneNumber(phone, 60, function (credential)
```
I always get `error: unknown error verifying number`

**Comment by rolinger** [comment]
Since @apptum got it working on Android 7.1, my guess is that this fork is not backward compatible with Android 6x...or probably even 5x.

**Comment by brunosoaresds** [comment]
@sajTempler its probably an error in your app configuration in the firebase. did you added the app SHA1 fingerprint? take a look in #418

**Comment by sajTempler** [comment]
@brunosoaresds yes I solved this couple days ago, in deed this was SHA-1 concern. As well maven repository (as in your pull request). Thanks

**Comment by robertarnesson** [comment]
closing this since a newer PR has been merged

**Pull request closed without merging**
