### PR TITLE
Fix 'plugin create an extra Resources folder inside Resources with an empty google-info.plist'

### PR DESCRIPTION
**Pull request by wolfg1969**
The cause  is https://github.com/apache/cordova-ios/pull/310/files.

### CODE REVIEW

**Comment by wolfg1969** [comment]
#327

**Comment by soumak77** [comment]
@robertarnesson Can this get published with a new release?  iOS builds for this plugin appear to have been broken as a result of the cordova fix.

**Comment by soumak77** [comment]
@robertarnesson thanks for merging this!  Could you publish a patch release so I can try out the new build?

**Comment by robertarnesson** [comment]
@soumak77 you can try it from master without a release. will release when all changes are confirmed working :)

**Comment by soumak77** [comment]
@robertarnesson wasn't sure how to do that at first, but I figured it out.  Testing now.

I think https://github.com/arnesson/cordova-plugin-firebase/commit/9eecdf9c814cad4e3588ed23276da1b76b4be438 might have fixed the iOS build but wasn't part of the latest release.  With #328 integrated, you might be able to revert the other change.

**Comment by soumak77** [comment]
@robertarnesson without any changes the following error occurs:
```
Executing script found in plugin cordova-plugin-firebase for hook "after_prepare": plugins/cordova-plugin-firebase/scripts/after_prepare.js
Error: Invalid data, chunk must be a string or buffer, not object
```

I had to revert change https://github.com/arnesson/cordova-plugin-firebase/commit/9eecdf9c814cad4e3588ed23276da1b76b4be438 to fix the issue

**Comment by soumak77** [comment]
@robertarnesson taking into account the discussion from https://github.com/arnesson/cordova-plugin-firebase/pull/295, it might be best to just revert this change and let https://github.com/arnesson/cordova-plugin-firebase/commit/9eecdf9c814cad4e3588ed23276da1b76b4be438 fix the issue.  https://github.com/arnesson/cordova-plugin-firebase/commit/9eecdf9c814cad4e3588ed23276da1b76b4be438 wasn't part of the latest release so I didn't realize that fixed the build.

**Comment by robertarnesson** [comment]
@soumak77 yeah I think you're right

**Comment by soumak77** [comment]
@robertarnesson this change needs to be re-added after #364 was merged

**Pull request merged**
