### PR TITLE
Move from Firebase Crash to Firebase Crashlytics and stop opt-in users

### PR DESCRIPTION
**Pull request by gvieduc**
Hi,

I worked on your plugin to use Firebase Crashlytics instead of Crash because it stop on 9/9.
I succeed to use Firebase Crashlytics with Google Service and without Fabric API key.
Moreover I modified the way Firebase is initialized, opt-in is disabled by default to be GDPR compliant. Now you'll have to initialize each Firebase services to activate them so we'll can let user to choose to not use Google's services.

Lot's of files and ideas come from [](https://github.com/sarriaroman/FabricPlugin).

Disclaimer : I'm beginner with Cordova plugins and it's the first time I develop in Objective-C ! Every advise on the way I did this are welcome.

Thanks for reading me,

Guillaume (or William in english :) )

### CODE REVIEW

**Comment by StephanMeijer** [comment]
Is this a working solution for Android?

**Comment by StephanMeijer** [comment]
Lot of files changed..?

**Comment by gvieduc** [comment]
We're using it in development for now, it seem to be working. It only connect if you initialize Firebase and Firebase's Crashlytics was enabled after using it.
See my fork for last commit for iOS.

**Comment by StephanMeijer** [comment]
Do you have any code examples on initializing Firebase?

**Comment by gvieduc** [comment]
No but take a look at the file : www/firebase.js
I added initialization functions.

exports.initFirebase = function (success, error) 
exports.initCrashlytics = function (success, error)
exports.initAnalytics = function (success, error) 
exports.initPerformance = function (success, error)
exports.initRemoteConfig = function (success, error)

**Comment by StephanMeijer** [comment]
Thanks

**Comment by StephanMeijer** [comment]
Can you undo your stylechanges, please? (e.g. spacing)

**Comment by gvieduc** [comment]
I'll do it, but not for now, I don't have the time to.

**Comment by gvieduc** [comment]
Hi,
I used  scripts/lib/android-helper.js from the official Crashlytics plugin. It add "apply plugin: 'com.google.gms.google-services'" in the top of the main Gradle file and so use google-service.json to read these values.
As what I've seen it's working in this configuration but I'm listening to all of your ideas.

Guillaume

**Comment by BluebambooSRL** [comment]
Hi @StephanMeijer @soumak77 could you please merge?
Thanks in advance
Federico

**Comment by bensinclair** [comment]
+1 on merging

**Comment by StephanMeijer** [comment]
Merging would be nice, indeed.

**Comment by Victordgrandis** [comment]
+1 on merging

**Comment by soumak77** [comment]
PR has been merged and is available in [v1.1.0](https://github.com/arnesson/cordova-plugin-firebase/releases/tag/v1.1.0)

**Comment by briantq** [comment]
@soumak77 I am 99% sure this breaks crash reporting on iOS.  Looking at the documentation, Crashlytics requires a build phase to be added and it isn't added.  By removing the Firebase Crash framework, iOS has no working crash reporting framework.

Do PRs typically have documentation updates also?  By changing the behavior of the way Firebase initializes, along with the new JS APIs, this will likely cause problems when people adopt the plugin and can't understand why it isn't working.

**Comment by soumak77** [comment]
@briantq in hindsight I should have released these changes under a major release (`2.0.0`) instead of a minor release (`1.1.0`) due to all the breaking changes.  PRs should add documentation changes when necessary, however, many people requested this PR merged so I assumed it had been tested by the community, but apparently it wasn't fully tested on all platforms.

I don't have time to manually test every PR, so I am relying on the community to test and verify that newly released versions and proposed PRs are working as desired.  Worst case, users can hardcode the version of the plugin that is working for them.  I understand how annoying this can be, but that is just part of dealing with open source projects.

**Comment by soumak77** [comment]
@gvieduc could you please provide a PR with updates to the README so that others are able to understand exactly what is required to get Crashlytics working on android and iOS?  It appears there are some manual steps required that are not easy to figure out.

If someone else from the community could provide this info, I'll gladly accept the PR

**Comment by soumak77** [comment]
It appears this PR removed the auto-init functionality.  Would any be able to help investigate and figure out what code needs to be added back to fix this?  I would love to accept a PR and push out a new patch release so that those adopting v1.1.x don't have to change their code to get the plugin to work as it used to work (i.e. no breaking changes).

If needed, we can add a cordova configuration variable which disables the auto-init functionality.

**Comment by StephanMeijer** [comment]
Is the functionality in this PR still working and merged into the master-branch? cc @soumak77

**Comment by soumak77** [comment]
@StephanMeijer yes this has been merged though it only worked on android.  #836 fixed this on iOS.  We still need #832 tested then I'll release a new version.

**Pull request merged**
