### PR TITLE
Unregister method added.

### PR DESCRIPTION
**Pull request by hardikthakkar3**
Added unregister method, which deletes old firebase instanceID and recreates newinstance and also new token. 
This thing is useful when user logout from the app and still getting notifications.

### CODE REVIEW

**Comment by robertarnesson** [comment]
Great. can you just revert the version number changes? its done separately at release

**Comment by jpfsilva** [comment]
@hardikthakkar3 what about if we just wanted to unregister the token and not recreate a new one? shouldn't it be 2 diferent methods so the developers can have more freedom in coding?
But thank you for this method, It would help lots of us!

**Comment by hardikthakkar3** [comment]
@robertarnesson I have reverted version number changes.

**Comment by hardikthakkar3** [comment]
@jpfsilva Yes, you are right. You can do this once this is merged. 
My thought was, once a user logout, instance & token is deleted. 
However, user can login again the same moment, maybe with separate credentials, that time we will have to wait for new instance & token creation.

**Comment by rhernandez-domandtom** [comment]
Is this already available to use? I'm on 0.1.21 and is giving me undefined

**Comment by hardikthakkar3** [comment]
Reinstall the plugin in your app, because version was not updated when I added this method.

Excuse Typos,

**Comment by rhernandez-domandtom** [comment]
I just reinstalled the plugin, is still giving me undefined.. still using the version 0.1.21 is there a version update ?

**Comment by peterlai107** [comment]
+1

**Comment by jschroeerluecke** [comment]
I can't register again. I have a settings menu where the user can disable or enable the push notifications. When the user disables it, I use the unregister method. And when the user enables the push notifications, I use the getToken method, but after I used unregister I can't receive any messages anymore with the getToken method. Help me please !

**Comment by zgluis** [comment]
What if the user logs out with the Airplane Mode on?

**Pull request merged**
