### PR TITLE
Fix Android N crash when notification.contentView is null

### PR DESCRIPTION
**Pull request by johncblandii**
> The view that will represent this notification in the notification list (which is pulled down from the status bar). As of N, this field may be null. The notification view is determined by the inputs to Notification.Builder; a custom RemoteViews can optionally be supplied with setCustomContentView(RemoteViews).

https://developer.android.com/reference/android/app/Notification.html#contentView

### CODE REVIEW

**Comment by johncblandii** [comment]
@robertarnesson, this was crashing repeatedly on my Pixel. Wrapping an `if` stopped the crash.

**Comment by robertarnesson** [comment]
nice!

**Comment by eros2187** [comment]
Hi guys i can i know which plugin version works with ios? Do some plugin branches I can try?
I'm a bit confused by reading several posts .. I do not understand what the stable one is hoping to receive thanks thank you

**Comment by johncblandii** [comment]
@eros2187, I'm using master and it works in iOS.

**Comment by eros2187** [comment]
I'm experiencing this error by sending a notification ios me from InvalidApnsCredential error
The certificate was generated and it has not expired and was exported and loaded into p12 in the firebase console
Sending the message from the firebase console by the same error
This and the script I use to send the message the same script for android works perfectly.

<?php
// API access key from Google API's Console
define( 'API_ACCESS_KEY', 'KEY SERVER ME' );
//$registrationIds = array( $_GET['id'] );
//https://developers.google.com/cloud-messaging/http-server-ref

$token = 'TOKEN ME';
$registrationIds = array($token);

// prep the bundle
/*$msg = array
(
	'body' 	=> $_GET['body'],
	'title'		=> $_GET['title'],
	'vibrate'	=> 1,
	'sound'		=> 1,
);
*/
$msg = array
(
	'body' 	=> 'prova',
	'title'		=> 'notifica',
	'vibrate'	=> 1,
	'icon'	=> 'myicon',/*Default Icon*/
	'sound'		=> 1,
	'color'		=> '#E21F1F'
);
$fields = array
(
	'registration_ids' 	=> $registrationIds,
	'notification'			=> $msg
);
 
$headers = array
(
	'Authorization: key=' . API_ACCESS_KEY,
	'Content-Type: application/json'
);
 
$ch = curl_init();
curl_setopt( $ch,CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send' );
$priority="high";
curl_setopt( $ch,CURLOPT_POST, true );
curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
$result = curl_exec($ch );
curl_close( $ch );
echo $result;
?>
You have the same problem know how can I solve it?

**Comment by johncblandii** [comment]
Oh, that's unrelated to this lib. Have you updated your Firebase plist?

**Comment by eros2187** [comment]
What do you mean to update the plist? Does the json configuration file of google tell you?

**Comment by johncblandii** [comment]
The Firebase console provides a plist file for iOS and json for Android. Make sure those are in the root of your project and this plugin will move them into place.

**Comment by eros2187** [comment]
OK THIS IS NOW BACK NOW
WOULD IT WOULD BE GREAT IF IT WAS A PROJECT WE WANT TO SEE YOU CAN POST A DEMO PROJECT?
Did you test with ios version 10 and does the right notifications work even with earlier versions?

**Comment by johncblandii** [comment]
I would suggest adding an Issue with a request for a demo project or provide one in a PR.

Glad you're back up and running.

**Comment by eros2187** [comment]
Using the plugin I'm noticing that if I call the function as well as you see without calling the grantpermission () function the message is sent but I do not see any notification here is the code

`document.addEventListener('deviceready', onDeviceReady, false);

function onDeviceReady() {
$('#console').append('START');
setTimeout(getTheToken, 1000);
}

function getTheToken() {
window.FirebasePlugin.getToken(function(token) {
            if (token == null) {
                console.log("null token");
                setTimeout(getTheToken, 1000);
            } else {
                //window.FirebasePlugin.grantPermission();
                $('#console').append('token: ' + token);
                console.log("I got the token: " + token);
            }
        },
        function (error) {
            $('#consoleerr').append('error retrieving token: ' + error);
        }
    );
}
`
server
{"multicast_id":7649446427278374045,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1494347311775201%812d9b5d812d9b5d"}]}


**If I lose the grantPermission () function, the server returns me**

`{"multicast_id":6314053970229096456,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"InvalidApnsCredential"}]}
my device is ipad mini 10.3.1 

**As can be solved?**

**Pull request merged**
