### PR TITLE
setup [FIRapp configureWithOptions] passing Google .plist

### PR DESCRIPTION
**Pull request by chrisid**
Fix for issue #866 
Gets path for GoogleService-Info.plist and pass it as a parameter to FIRApp configureWithOptions

### CODE REVIEW

**Comment by briantq** [comment]
@chrisid Any idea why this is needed?  I took a quick look at that method you reference and the only documentation that is provided is related to multiple projects and dynamically loading plists.  From your code submission I don't think you are trying to load different plists, just the default one.  I was trying to figure out _why_ that is required.

**Comment by soumak77** [comment]
@briantq based on the issue description, it might be an issue with iOS 12

**Comment by soumak77** [comment]
Though if I were to have read the other comments, the issue is also being seen on iOS 11.  Perhaps it's an issue with xcode 10?

**Comment by chrisid** [comment]
@briantq I don't know why that's exactly needed but it's the only way I was able to get it working again. When the file is not passed, FIRApp does not find it and silently fails to configure. I'd love to understand why.

@soumak77 I also tried XCode 9 iOS 11 and the same happened.

**Comment by soumak77** [comment]
@briantq when you have a chance, could you verify this works with your app?  So long as it doesn't break anything it seems fine to merge.

**Comment by briantq** [comment]
@soumak77 my project is in a bad state at the moment (still trying to figure out why...).  One thing that crossed my mind is that if we think this is a XCode 10 issue that we might see if upgrading FIrebase resolves the issue (they might have included a fix for something).  The current verision is 5.9.0 while we are using 5.7.0.

**Comment by soumak77** [comment]
Based on @chrisid comments, it also happens with xcode 9. There is a [known issue](https://github.com/apache/cordova-ios/issues/407) with cordova-ios supporting xcode 10, but I'm not sure of that is related.

**Comment by soumak77** [comment]
It wouldn't hurt to upgrade the firebase SDK, but I don't think it'll fix this issue

**Comment by briantq** [comment]
@soumak77 Thanks for mentioning about the known issue in XCode 10, that was why I was not able to get anything to work.  I did test with the branch and after using the work around, did see notifications so I think the PR works.

**Pull request merged**
