### PR TITLE
Update FirebasePluginMessagingService.java - replace default notificaiton icon, the easy way

### PR DESCRIPTION
**Pull request by FreezyExp**
add bigicon and replace small icon using drawables defined in styles.
you can add a styles as well as the drawbles to the 
res/native/android/ folder

values/styles.xml
and 
values-v21/styles.xml

<?xml version="1.0" encoding="utf-8" ?>
<resources>
        <drawable name="notification_big">@mipmap/icon</drawable>
        <drawable name="notification_icon">@drawable/ic_silhouette</drawable>
</recources

### CODE REVIEW

**Comment by robertarnesson** [comment]
@FreezyExp can you also update the notification icon instructions in the readme?

**Comment by FreezyExp** [comment]
Done, not sure I did it properly (both github and readme wording) but patch-2 now has an updated readme

**Comment by FreezyExp** [comment]
Alright, it should be ready now :P

**Comment by FreezyExp** [comment]
sorry for the stack of commits, lots of proof reading edits and formatting.
I think it's done now

**Comment by swbradshaw** [comment]
@FreezyExp I'm not understanding how your documentation is correct with cordova. As far as I know, you can't put files in <projectroot>/res/native/android/res/value and have these be copied on build. At least not without a hook like this one: https://github.com/Microsoft/cordova-samples/blob/master/cordova-hooks/cordova-plugin-res-native/hooks/hook-res-native.js

I tried this myself with Cordova 6.3.1 and had no luck in getting these files to copy. I manually put them in correct Android platform folders and was able to build, but sadly my notification is still showing as a white box :-(

**Comment by FreezyExp** [comment]
sorry this was my first cordova related experience, so I might have skipped a step or two
lets get debugging

Cordova CLI 6.4.0

<engine name="android" spec="~6.1.2" />

these two might be relevant:
 <plugin name="cordova-custom-config" spec="~3.1.2" />
 <plugin name="cordova-plugin-compat" version="1.1.0" />

**Pull request merged**
