### PR TITLE
IOS-ANDROID PHONE AUTH

### PR DESCRIPTION
**Pull request by jestcastro**
I just modified the plugin cordova-firebase-plugin
BASED ON THE CONTRIBUTIONS OF
https://github.com/silverio/ 
and
https://github.com/apptum/

Works good!

### CODE REVIEW

**Comment by condorman** [comment]
Thank you!!!!!! Android auth works correctly!

**Comment by FallenRiteMonk** [comment]
Doesn't work for me. After installing using:
```
cordova plugin add https://github.com/jestcastro/cordova-plugin-firebase
```
and running on android, I get the following error:
```
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/ma;
```

**Comment by FallenRiteMonk** [comment]
@robertarnesson could you please comment on this PR.
I would be very interested in getting this merged, but if you say that this is out of scope of your plugin, please let me know and we might be able to make it own plugin for it!
Otherwise let us know what needs to be done so that it gets merged.

Thanks

**Comment by FallenRiteMonk** [comment]
@jestcastro what do you think about creating you own plugin 'cordova-plugin-firebase-phoneauth' or something like that, with just your part of the code?

Or would you mind if I would do it?

**Comment by jestcastro** [comment]
@FallenRiteMonk 
Let's create it!
At this moment I am a little busy but I just created this repository https://github.com/jestcastro/cordova-firebase-phoneauth, if you want you can clone it and add the part of ios or android to get started

**Comment by apptum** [comment]
@FallenRiteMonk it's dangerous to go alone... take this
https://github.com/apptum/cordova-plugin-firebase

**Comment by FallenRiteMonk** [comment]
@apptum I would, but you only support phone login for android and i need ios as well!
But would you accept/merge this PR (phone login for android and ios) if @jestcastro would propose it to your repo?

**Comment by robertarnesson** [comment]
I'd like to include this. have you tested on ios?

**Comment by jestcastro** [comment]
@robertarnesson  yes, it's working

**Comment by GulinSS** [comment]
Do we have any news regarding that?

**Comment by GulinSS** [comment]
@robertarnesson

**Comment by cmartin81** [comment]
+1

**Comment by FallenRiteMonk** [comment]
@jestcastro could you please fix the conflicts so we can get this merged sometime soon?

**Comment by tawakol** [comment]
+1

**Comment by sajTempler** [comment]
okay. This fork works fine.
```
Ionic 3.6.0
Android 6
```

**Comment by 0s1r1s** [comment]
I also get this Error: 
```
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzev;
```
Shouldn't this problem be solved in the current version? The build.gradle looks fine.

**Pull request merged**
